In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
for i in list_:
    data_type = type(i)
    print(f"The data type of {i} is {data_type}")

The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>


In [8]:
for i in array_list:
    print(f"The data type of {i} is {type(i)}")

The data type of 1 is <class 'numpy.str_'>
The data type of 2 is <class 'numpy.str_'>
The data type of 3 is <class 'numpy.str_'>
The data type of 4 is <class 'numpy.str_'>
The data type of 5 is <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
for i in list_:
    print(f"The data type of {i} is {type(i)}")

The data type of 1 is <class 'str'>
The data type of 2 is <class 'str'>
The data type of 3 is <class 'str'>
The data type of 4 is <class 'str'>
The data type of 5 is <class 'str'>


In [16]:
for i in array_list:
    print(f"The data type of {i} is {type(i)}")

The data type of 1 is <class 'numpy.int32'>
The data type of 2 is <class 'numpy.int32'>
The data type of 3 is <class 'numpy.int32'>
The data type of 4 is <class 'numpy.int32'>
The data type of 5 is <class 'numpy.int32'>


In [17]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object=num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [18]:
num_array.shape

(2, 3)

In [19]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
z_array = np.zeros((3,3))

In [24]:
z_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
z_array.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions? 
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
id_matrix = np.eye(5,5)

In [31]:
id_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])